## For ccache using commands from https://pat-s.me/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
language: r
os:
  - linux
  - osx
  
sudo: false
cache: packages
cache:
  - $HOME/.ccache

addons:
  apt:
    packages:
     - ccache
r:
  - release
  
r_packages:
  - testthat 
  - devtools 

before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - R -q -e "install.packages('devtools')"
#  - make ./AntMAN/NAMESPACE
  - cd AntMAN
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always
