language: r
os:
  - linux
  - osx
  
sudo: false
cache: packages

r:
  - release

before_install:
  - cd AntMAN
  
warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always
